//! Shell alias blocks. Aliases are auto-edited into reversible, marker-delimited
//! blocks so vhrn can regenerate or remove them cleanly without disturbing the rest
//! of an rc file. Ports the pure rendering from alias.go; the rc-file writing and
//! the installed-registry read land in a later phase.

use crate::harness::Harness;

const ALIAS_START: &str = "# >>> vhrn managed aliases >>>";
const ALIAS_END: &str = "# <<< vhrn managed aliases <<<";

/// Render one alias in a shell's syntax. fish's alias takes a space-separated
/// definition and appends $argv itself; bash/zsh use name=value.
fn alias_line(shell: &str, name: &str, target: &str) -> String {
    if shell == "fish" {
        format!("alias {name} '{target}'")
    } else {
        format!("alias {name}='{target}'")
    }
}

/// Build the managed block (markers + one alias per installed harness) for a shell,
/// or "" when nothing is installed so the block is removed entirely.
fn alias_block(hs: &[Harness], shell: &str) -> String {
    if hs.is_empty() {
        return String::new();
    }
    let mut b = String::new();
    b.push_str(ALIAS_START);
    b.push('\n');
    b.push_str("# Regenerated by vhrn install/uninstall; edits here are overwritten.\n");
    for h in hs {
        b.push_str(&alias_line(shell, &h.alias, &format!("vhrn {}", h.name)));
        b.push('\n');
    }
    b.push_str(ALIAS_END);
    b.push('\n');
    b
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alias_line_syntax() {
        assert_eq!(alias_line("zsh", "claude", "vhrn claude"), "alias claude='vhrn claude'");
        assert_eq!(alias_line("fish", "claude", "vhrn claude"), "alias claude 'vhrn claude'");
    }

    #[test]
    fn alias_block_markers_and_lines() {
        assert_eq!(alias_block(&[], "zsh"), "", "empty harness set yields no block");
        let h = Harness { name: "claude".into(), alias: "claude".into(), ..Default::default() };
        let b = alias_block(std::slice::from_ref(&h), "bash");
        assert!(b.contains(ALIAS_START) && b.contains(ALIAS_END), "block missing markers:\n{b}");
        assert!(b.contains("alias claude='vhrn claude'"), "block missing alias line:\n{b}");
    }
}
